language: c
script: make release
before_install:
  - sudo add-apt-repository "deb ${CRAN}/bin/linux/ubuntu $(lsb_release -cs)/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-base-dev qpdf
  - Rscript --version
branches:
  only:
    - master
    - /^v[0-9.]+$/
