language: r
sudo: required

warnings_are_errors: true

r_binary_packages:
  - testthat
  - ff 
  - bigmemory 
  - RcppArmadillo
  - igraph 
  - stringdist 
  - shiny

r_github_packages:
  - jimhester/lintr 
  - jimhester/covr

after_success:
  - Rscript -e "lintr::lint_package()"
  - Rscript -e "library(covr); coveralls()"

