# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
env:
 global:
   - CRAN: http://cran.rstudio.com
   - R_BUILD_ARGS="--no-build-vignettes --no-manual"
   - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
   - BOOTSTRAP_LATEX=""
   - WARNINGS_ARE_ERRORS=1
script: make travis-test
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_github hadley/dplyr
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh r_install knitr
  - ./travis-tool.sh aptget_install seq-gen
after_failure:
  - ./travis-tool.sh dump_logs
