language: r
sudo: required

warnings_are_errors: true

r_binary_packages:
  - testthat
  - covr
  - RcppArmadillo # for coala
  - knitr # for lintr
  - igraph # for lintr
  
r_packages:
  - lintr 

after_success:
  - Rscript -e "lintr::lint_package()"
  - Rscript -e "library(covr); coveralls()"

notifications:
  email: false

