language: c

env:
  global:
  - WARNINGS_ARE_ERRORS=1
sudo: required

before_install:
  - rm .Rprofile
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh r_binary_install ff bigmemory ape RcppArmadillo
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh aptget_install seq-gen

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - ./travis-tool.sh r_binary_install igraph stringdist shiny
  - ./travis-tool.sh install_github jimhester/lintr jimhester/covr 
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
