language: c
env:
  global:
  - CRAN: http://cran.rstudio.com
  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
  - BOOTSTRAP_LATEX=""
  - WARNINGS_ARE_ERRORS=1
script: 
  - ./travis-tool.sh run_tests
  - ./tests/integration/run-tests.R
before_install:
- rm .Rprofile
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh install_github scrm/scrm-r
- ./travis-tool.sh install_deps
- ./travis-tool.sh r_install roxygen2
- ./travis-tool.sh github_package jimhester/covr
- ./travis-tool.sh aptget_install seq-gen
- wget http://www.mabs.at/ewing/msms/msms3.2rc-b163.jar && sudo mv msms3.2rc-b163.jar /usr/local/bin/msms.jar
after_failure:
- ./travis-tool.sh dump_logs
- Rscript -e 'library(covr);coveralls()'
notifications:
  email:
    on_success: always
    on_failure: always
